### PR TITLE
docs: AVNU, Pragma and Snapshot X audits

### PR DESCRIPTION
**Pull request by milancermak**
Adding audit reports of AVNU, Pragma and Snapshot X.

## Checklist

- [x] The URL is not already present in the list (check with CTRL/CMD+F in the
      raw markdown file).
- [x] Each description starts with an uppercase character and ends with a
      period.<br>Example: `cairo - The Cairo programming language.`
- [x] Drop all `A` / `An` prefixes at the start of the description.

### CODE REVIEW

**Comment by milancermak** [comment]
Test fails on a thing I didn't touch 🤷

**Comment by robertkodra** [comment]
Nice, I saw that Avnu is missing, could you add that as well on this PR? @milancermak  

https://github.com/NethermindEth/PublicAuditReports/blob/main/NM0141-FINAL_AVNU.pdf

**Comment by milancermak** [comment]
Oooh, I missed AVNU's report. Thanks, will add (and read 🤓 ).

**Comment by amanusk** [comment]
Thank you for the great additions!

**Pull request merged**
